const fs = require('fs');
const path = require('path');

// Reproducible build artifacts & generated outputs.
// None of these are committed to git — they are rebuilt by the dev/build
// scripts (copy-assets, build-search-index, next build). Safe to delete any
// time; run `npm run clean` when no dev server is running for a pristine tree.
const targets = [
  '.next',                      // Next.js build/dev cache & output
  'out',                        // Next.js static export (if ever produced)
  'public/content',            // copied from content/ by copy-assets
  'public/search-index.json',  // generated by build-search-index
  'tsconfig.tsbuildinfo',      // TypeScript incremental build cache
];

let removed = 0;

for (const relativePath of targets) {
  const absolutePath = path.join(process.cwd(), relativePath);

  if (fs.existsSync(absolutePath)) {
    fs.rmSync(absolutePath, { recursive: true, force: true });
    console.log(`Removed: ${relativePath}`);
    removed += 1;
  }
}

console.log(
  removed > 0
    ? `Clean complete — removed ${removed} item(s).`
    : 'Nothing to clean — the tree is already pristine.',
);
